spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 2000000
      maximum-pool-size: 40
      minimum-idle: 20
    url: secret
    username: secret
    password: secret
  config:
    activate:
      on-profile:
  thread:
    queueCapacity: 10
    maxPoolSize: 100
    prefix: Fundiin-Thread
    corePoolSize: 50